default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tehnoholod_db_dev

test:
  <<: *default
  database: tehnoholod_db_test

production:
  <<: *default
  username: deploy
  database: tehnoholod_db
  # password: <%= ENV['CINEMAFULL_DATABASE_PASSWORD'] %>
